compatibility_date = "2022-12-07"
name = "noice-memos"
r2_buckets = [
  {binding = "memos_bucket", bucket_name = "memos", preview_bucket_name = "memos-preview"},
]
[[d1_databases]]
binding = "DB"
database_id = "016423dd-c191-4088-8f67-0aab681ebcb9"
database_name = "noice"
preview_database_id = "016423dd-c191-4088-8f67-0aab681ebcb9"

# SECRETS
# GH_CLIENT_ID
# GH_CLIENT_SECRET
